#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Filter.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Filter : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<div class=\"btn-toolbar-label btn-toolbar-label-sm pull-left\" style=\"margin-lef" +
"t: 5px;\">\r\n    Filter by type:\r\n</div>\r\n<div class=\"btn-toolbar-spacer pull-left" +
"\"></div>\r\n<div class=\"btn-group pull-left\">\r\n    <a class=\"btn btn-sm btn-defaul" +
"t ");


            
            #line 10 "..\..\Dashboard\Pages\_Filter.cshtml"
                                 Write(null == _pager.TypeFilter ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 10 "..\..\Dashboard\Pages\_Filter.cshtml"
                                                                                      Write(_pager.TypeFilterUrl(null));

            
            #line default
            #line hidden
WriteLiteral("\">All</a>\r\n    <a class=\"btn btn-sm btn-default ");


            
            #line 11 "..\..\Dashboard\Pages\_Filter.cshtml"
                                 Write("Information" == _pager.TypeFilter ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 11 "..\..\Dashboard\Pages\_Filter.cshtml"
                                                                                               Write(_pager.TypeFilterUrl("Information"));

            
            #line default
            #line hidden
WriteLiteral("\">Information</a>\r\n    <a class=\"btn btn-sm btn-default ");


            
            #line 12 "..\..\Dashboard\Pages\_Filter.cshtml"
                                 Write("Critical" == _pager.TypeFilter ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 12 "..\..\Dashboard\Pages\_Filter.cshtml"
                                                                                            Write(_pager.TypeFilterUrl("Critical"));

            
            #line default
            #line hidden
WriteLiteral("\">Critical</a>\r\n    <a class=\"btn btn-sm btn-default ");


            
            #line 13 "..\..\Dashboard\Pages\_Filter.cshtml"
                                 Write("Error" == _pager.TypeFilter ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 13 "..\..\Dashboard\Pages\_Filter.cshtml"
                                                                                         Write(_pager.TypeFilterUrl("Error"));

            
            #line default
            #line hidden
WriteLiteral("\">Error</a>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
