#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Filter.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Filter : RazorPage<Pager>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"btn-toolbar-label btn-toolbar-label-sm pull-left\"");

WriteLiteral(" style=\"margin-left: 5px;\"");

WriteLiteral(">\r\n    Filter by type:\r\n</div>\r\n<div");

WriteLiteral(" class=\"btn-toolbar-spacer pull-left\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" class=\"btn-group pull-left\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Dashboard\Pages\_Filter.cshtml"
Write(Html.Link("All", Model.TypeFilterUrl(null), "btn btn-sm btn-default", Model.TypeFilter == null));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Dashboard\Pages\_Filter.cshtml"
Write(Html.Link("Information", Model.TypeFilterUrl("Information"), "btn btn-sm btn-default", Model.TypeFilter == "Information"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Dashboard\Pages\_Filter.cshtml"
Write(Html.Link("Critical", Model.TypeFilterUrl("Critical"), "btn btn-sm btn-default", Model.TypeFilter == "Critical"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Dashboard\Pages\_Filter.cshtml"
Write(Html.Link("Error", Model.TypeFilterUrl("Error"), "btn btn-sm btn-default", Model.TypeFilter == "Error"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"btn-group pull-left\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" id=\"search-button-on\"");

WriteLiteral(" class=\"btn btn-sm btn-default\"");

WriteLiteral(">Search</button>\r\n    <a");

WriteLiteral(" id=\"search-button-off\"");

WriteLiteral(" class=\"btn btn-sm btn-success hide\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1020), Tuple.Create("\"", 1038)
            
            #line 18 "..\..\Dashboard\Pages\_Filter.cshtml"
, Tuple.Create(Tuple.Create("", 1027), Tuple.Create<System.Object, System.Int32>(Url.Home()
            
            #line default
            #line hidden
, 1027), false)
);

WriteLiteral(@">
        Search
    </a>
</div>

<script>
    var searchButtonOn = document.getElementById('search-button-on');
    var searchButtonOff = document.getElementById('search-button-off');

    Date.prototype.addHours = function (h) {
        this.setHours(this.getHours() + h);
        return this;
    }

    searchButtonOn.onclick = function () {
        console.log(""show first search"");
        var searchBar = document.getElementById('search-bar');
            searchButtonOn.classList.add('hide');
            searchBar.classList.remove('hide');
            searchButtonOff.classList.remove('hide');
            document.getElementById('search-from').valueAsDate = new Date();
            document.getElementById('search-to').valueAsDate = new Date().addHours(24);
            document.getElementById('search-value').focus();
    }
</script>");

        }
    }
}
#pragma warning restore 1591
