#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Paginator.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Paginator : RazorPage<Pager>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"btn-toolbar\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Dashboard\Pages\_Paginator.cshtml"
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Dashboard\Pages\_Paginator.cshtml"
         if (Model.TotalPageCount > 1)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"paginatorId\"");

WriteLiteral(" class=\"btn-group paginator\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Dashboard\Pages\_Paginator.cshtml"
                
            
            #line default
            #line hidden
            
            #line 8 "..\..\Dashboard\Pages\_Paginator.cshtml"
                 foreach (var page in Model.PagerItems)
                {
                    switch (page.Type)
                    {
                        case Pager.ItemType.Page:
                            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Dashboard\Pages\_Paginator.cshtml"
                       Write(Html.Link(page.PageIndex.ToString(), Model.PageUrl(page.PageIndex), "btn btn-default", Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                                        
                            break;
                        case Pager.ItemType.NextPage:
                        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Dashboard\Pages\_Paginator.cshtml"
                   Write(Html.Link("Next", Model.PageUrl(page.PageIndex), "btn btn-default", isDisabled: Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                             
                            break;
                        case Pager.ItemType.PrevPage:
                        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Dashboard\Pages\_Paginator.cshtml"
                   Write(Html.Link("Prev", Model.PageUrl(page.PageIndex), "btn btn-default", isDisabled: Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                             
                            break;
                        case Pager.ItemType.MorePage:

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default disabled\"");

WriteLiteral(">…</a>\r\n");

            
            #line 23 "..\..\Dashboard\Pages\_Paginator.cshtml"
                            break;
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"btn-toolbar-spacer\"");

WriteLiteral("></div>\r\n");

            
            #line 28 "..\..\Dashboard\Pages\_Paginator.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"btn-toolbar-label\"");

WriteLiteral(">Total items: ");

            
            #line 30 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                           Write(Model.TotalRecordCount);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    var searchValue = document.getElementById('search-value').value;
    if (searchValue != """") {
        var paginator = document.getElementById('paginatorId');
        if (paginator != null) { 
            paginator.classList.add('hide');
        }
    }
</script>");

        }
    }
}
#pragma warning restore 1591
