#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Paginator.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Paginator : RazorPage<Pager>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("<div class=\"row\">\r\n    <div class=\"col-lg-6\">\r\n        <p class=\"form-control-sta" +
"tic input-sm\">Total items: ");


            
            #line 6 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                        Write(Model.TotalRecordCount);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </div>\r\n    <div class=\"col-lg-6\">\r\n        <div class=\"pull-right\">\r\n");


            
            #line 10 "..\..\Dashboard\Pages\_Paginator.cshtml"
             if (Model.TotalPageCount > 1)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div id=\"paginatorId\" class=\"btn-group paginator\">\r\n");


            
            #line 13 "..\..\Dashboard\Pages\_Paginator.cshtml"
                     foreach (var page in Model.PagerItems)
                {
                    switch (page.Type)
                    {
                        case Pager.ItemType.Page:
                                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Dashboard\Pages\_Paginator.cshtml"
                           Write(Html.Link(page.PageIndex.ToString(), Model.PageUrl(page.PageIndex), "btn btn-sm btn-default", Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                                                   
                                break;
                            case Pager.ItemType.NextPage:
                                
            
            #line default
            #line hidden
            
            #line 21 "..\..\Dashboard\Pages\_Paginator.cshtml"
                           Write(Html.Link("Next", Model.PageUrl(page.PageIndex), "btn btn-sm btn-default", isDisabled: Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                                            
                                break;
                            case Pager.ItemType.PrevPage:
                                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Dashboard\Pages\_Paginator.cshtml"
                           Write(Html.Link("Prev", Model.PageUrl(page.PageIndex), "btn btn-sm btn-default", isDisabled: Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                                            
                                break;
                            case Pager.ItemType.MorePage:

            
            #line default
            #line hidden
WriteLiteral("                                <a href=\"#\" class=\"btn btn-sm btn-default disable" +
"d\">…</a>\r\n");


            
            #line 28 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                break;
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");


            
            #line 32 "..\..\Dashboard\Pages\_Paginator.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>
    </div>
</div>

<script type=""text/javascript"">
    var searchValue = document.getElementById('search-value').value;
    if (searchValue != """") {
        var paginator = document.getElementById('paginatorId');
        if (paginator != null) { 
            paginator.classList.add('hide');
        }
    }
</script>");


        }
    }
}
#pragma warning restore 1591
