#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Paginator.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Paginator : RazorPage<Pager>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("<div class=\"btn-toolbar\">\r\n");


            
            #line 5 "..\..\Dashboard\Pages\_Paginator.cshtml"
     if (Model.TotalPageCount > 1)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"btn-group paginator\">\r\n");


            
            #line 8 "..\..\Dashboard\Pages\_Paginator.cshtml"
             foreach (var page in Model.PagerItems)
            {
                switch (page.Type)
                {
                    case Pager.ItemType.Page:
                        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Dashboard\Pages\_Paginator.cshtml"
                   Write(Html.Link(page.PageIndex.ToString(), Model.PageUrl(page.PageIndex), "btn btn-default", Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                                    
                        break;
                    case Pager.ItemType.NextPage:
                        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Dashboard\Pages\_Paginator.cshtml"
                   Write(Html.Link("Next", Model.PageUrl(page.PageIndex), "btn btn-default", isDisabled: Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                             
                        break;
                    case Pager.ItemType.PrevPage:
                        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Dashboard\Pages\_Paginator.cshtml"
                   Write(Html.Link("Prev", Model.PageUrl(page.PageIndex), "btn btn-default", isDisabled: Model.CurrentPage == page.PageIndex));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                                                                                                                             
                        break;
                    case Pager.ItemType.MorePage:

            
            #line default
            #line hidden
WriteLiteral("                        <a href=\"#\" class=\"btn btn-default disabled\">…</a>\r\n");


            
            #line 23 "..\..\Dashboard\Pages\_Paginator.cshtml"
                        break;
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");



WriteLiteral("        <div class=\"btn-toolbar-spacer\"></div>\r\n");


            
            #line 28 "..\..\Dashboard\Pages\_Paginator.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div class=\"btn-toolbar-label\">Total items: ");


            
            #line 30 "..\..\Dashboard\Pages\_Paginator.cshtml"
                                           Write(Model.TotalRecordCount);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
