#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class PerPageSelector : RazorPage<Pager>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" id=\"itemsPerPage\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"btn-group pull-right paginator\"");

WriteLiteral(">\r\n");

            
            #line 7 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
        
            
            #line default
            #line hidden
            
            #line 7 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
         foreach (var count in new[] { 10, 20, 50, 100, 500 })
        {
            
            
            #line default
            #line hidden
            
            #line 9 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
       Write(Html.Link(count.ToString(), Model.RecordsPerPageUrl(count), "btn btn-sm btn-default", count == Model.RecordsPerPage));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Dashboard\Pages\_PerPageSelector.cshtml"
                                                                                                                                 
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <div");

WriteLiteral(" class=\"btn-toolbar-spacer pull-right\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"btn-toolbar-label btn-toolbar-label-sm pull-right\"");

WriteLiteral(">\r\n        Items per page:\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
