#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Search.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Search : RazorPage<Pager>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" method=\"get\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-1 btn-toolbar-label\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"margin-left: 15px;\"");

WriteLiteral(">Search:</span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Find from:</label>\r\n                <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"from\"");

WriteAttribute("value", Tuple.Create(" value=\"", 544), Tuple.Create("\"", 572)
            
            #line 13 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 552), Tuple.Create<System.Object, System.Int32>(Model.GetFromTime()
            
            #line default
            #line hidden
, 552), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Find to:</label>\r\n                <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"to\"");

WriteAttribute("value", Tuple.Create(" value=\"", 751), Tuple.Create("\"", 777)
            
            #line 17 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 759), Tuple.Create<System.Object, System.Int32>(Model.GetToTime()
            
            #line default
            #line hidden
, 759), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Message contains:</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"val\"");

WriteAttribute("value", Tuple.Create(" value=\"", 966), Tuple.Create("\"", 997)
            
            #line 21 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 974), Tuple.Create<System.Object, System.Int32>(Model.GetSearchValue()
            
            #line default
            #line hidden
, 974), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" style=\"margin-top: 25px;\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n        </div>\r\n    </form>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
