#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Search.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Search : RazorPage<Pager>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" method=\"get\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-1 btn-toolbar-label\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"margin-left: 10px; padding-top: 30px;\"");

WriteLiteral(">Search:</span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Find from:</label>\r\n                <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"from\"");

WriteAttribute("value", Tuple.Create(" value=\"", 563), Tuple.Create("\"", 591)
            
            #line 13 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 571), Tuple.Create<System.Object, System.Int32>(Model.GetFromTime()
            
            #line default
            #line hidden
, 571), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Find to:</label>\r\n                <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"to\"");

WriteAttribute("value", Tuple.Create(" value=\"", 770), Tuple.Create("\"", 796)
            
            #line 17 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 778), Tuple.Create<System.Object, System.Int32>(Model.GetToTime()
            
            #line default
            #line hidden
, 778), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Message contains:</label>\r\n                <input");

WriteLiteral(" id=\"search-value\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"val\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1003), Tuple.Create("\"", 1034)
            
            #line 21 "..\..\Dashboard\Pages\_Search.cshtml"
            , Tuple.Create(Tuple.Create("", 1011), Tuple.Create<System.Object, System.Int32>(Model.GetSearchValue()
            
            #line default
            #line hidden
, 1011), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"type\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1088), Tuple.Create("\"", 1118)
            
            #line 22 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 1096), Tuple.Create<System.Object, System.Int32>(Model.GetFilterType()
            
            #line default
            #line hidden
, 1096), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" style=\"margin-top: 25px;\"");

WriteLiteral(@">Search</button>
            </div>
        </div>
    </form>
</div>

<script>
    var searchButton2 = document.getElementById('search-button');
    var searchValue = document.getElementById('search-value').value;
    if (searchValue != """") {
        searchButton.classList.add('btn-success');
        document.getElementById('search-bar').classList.remove('hide');
    }
</script>");

        }
    }
}
#pragma warning restore 1591
