#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\_Search.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Search : RazorPage<Pager>
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" method=\"get\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Find from:</label>\r\n                <input");

WriteLiteral(" id=\"search-from\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"from\"");

WriteAttribute("value", Tuple.Create(" value=\"", 422), Tuple.Create("\"", 450)
            
            #line 10 "..\..\Dashboard\Pages\_Search.cshtml"
             , Tuple.Create(Tuple.Create("", 430), Tuple.Create<System.Object, System.Int32>(Model.GetFromTime()
            
            #line default
            #line hidden
, 430), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Find to:</label>\r\n                <input");

WriteLiteral(" id=\"search-to\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"to\"");

WriteAttribute("value", Tuple.Create(" value=\"", 644), Tuple.Create("\"", 670)
            
            #line 14 "..\..\Dashboard\Pages\_Search.cshtml"
         , Tuple.Create(Tuple.Create("", 652), Tuple.Create<System.Object, System.Int32>(Model.GetToTime()
            
            #line default
            #line hidden
, 652), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2 form-group\"");

WriteLiteral(">\r\n                <label>Message contains:</label>\r\n                <input");

WriteLiteral(" id=\"search-value\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"val\"");

WriteAttribute("value", Tuple.Create(" value=\"", 877), Tuple.Create("\"", 908)
            
            #line 18 "..\..\Dashboard\Pages\_Search.cshtml"
             , Tuple.Create(Tuple.Create("", 885), Tuple.Create<System.Object, System.Int32>(Model.GetSearchValue()
            
            #line default
            #line hidden
, 885), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"type\"");

WriteAttribute("value", Tuple.Create(" value=\"", 962), Tuple.Create("\"", 992)
            
            #line 19 "..\..\Dashboard\Pages\_Search.cshtml"
, Tuple.Create(Tuple.Create("", 970), Tuple.Create<System.Object, System.Int32>(Model.GetFilterType()
            
            #line default
            #line hidden
, 970), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" style=\"margin-top: 25px;\"");

WriteLiteral(@">Search</button>
            </div>
        </div>
    </form>
</div>

<script>
    var searchButtonOn = document.getElementById('search-button-on');
    var searchButtonOff = document.getElementById('search-button-off');

    var searchValue = document.getElementById('search-value').value;
    if (searchValue != """") {
        searchButtonOn.classList.add('hide');
        searchButtonOff.classList.remove('hide');
        document.getElementById('search-bar').classList.remove('hide');
    }
</script>");

        }
    }
}
#pragma warning restore 1591
