#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DataObjectPage : RazorPage<DataObject>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral(@"<div class=""table-responsive"" style=""margin-bottom: 20px;"">
    <table class=""table table-striped table-bordered table-condensed"" style=""margin-bottom: 0;"">
        <thead>
            <tr class=""success"">
                <th>Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
");


            
            #line 13 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
             foreach(var row in Model.Rows)
            {
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
           Write(Html.DataRow(row));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
                                  
            }

            
            #line default
            #line hidden

            
            #line 17 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
             foreach (var obj in Model.Objects)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td colspan=\"2\" class=\"info\"><strong>");


            
            #line 20 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
                                                    Write(obj.Key);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n                </tr>\r\n");


            
            #line 22 "..\..\Dashboard\Pages\DataObjectPage.cshtml"

                foreach (var item in obj.Rows)
                {
                    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
               Write(Html.DataRow(item));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Dashboard\Pages\DataObjectPage.cshtml"
                                       
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
