#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\DataRowPage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DataRowPage : RazorPage<DataRow>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("<tr>\r\n    <td>");


            
            #line 5 "..\..\Dashboard\Pages\DataRowPage.cshtml"
   Write(Model.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    <td style=\"overflow: auto;\">\r\n        ");


            
            #line 7 "..\..\Dashboard\Pages\DataRowPage.cshtml"
   Write(Html.RenderValue(Model.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n</tr>");


        }
    }
}
#pragma warning restore 1591
