#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\HomePage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\HomePage.cshtml"
    using PugTrace.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\HomePage.cshtml"
    using PugTrace.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class HomePage : TracesPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\HomePage.cshtml"
  
    Layout = new LayoutPage();
    bool first = true;


            
            #line default
            #line hidden
WriteLiteral("<div class=\"btn-toolbar btn-toolbar-top\">\r\n    ");


            
            #line 11 "..\..\Dashboard\Pages\HomePage.cshtml"
Write(Html.Filter(this.Pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 12 "..\..\Dashboard\Pages\HomePage.cshtml"
Write(Html.PerPageSelector(this.Pager));

            
            #line default
            #line hidden
WriteLiteral(@"
</div>
<div class=""table-responsive"">
    <table class=""table"">
        <thead>
            <tr>
                <th>Application</th>
                <th>Source</th>
                <th>Id</th>
                <th>Event Type</th>
                <th>Timestamp</th>
                <th>Machine</th>
                <th>Message</th>
                <th style=""width: 70px;""></th>
            </tr>
        </thead>
        <tbody>
");


            
            #line 29 "..\..\Dashboard\Pages\HomePage.cshtml"
             foreach (var trace in this.Model)
            {
                var rowClass = "trace " + trace.EventType.ToLower();


            
            #line default
            #line hidden
WriteLiteral("                <tr class=\"");


            
            #line 33 "..\..\Dashboard\Pages\HomePage.cshtml"
                      Write(rowClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <td>");


            
            #line 34 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 35 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.Source);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 36 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 37 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.EventType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 38 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(Html.RenderDateTime(trace.UtcDateTime.ToLocalTime()));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 39 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");


            
            #line 40 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(Html.Truncate(trace.Message));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td><a href=\"");


            
            #line 41 "..\..\Dashboard\Pages\HomePage.cshtml"
                            Write(Url.TraceDetails(trace.TraceId.ToString()));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-xs btn-default pull-right\">Details</a></td>\r\n                </t" +
"r>\r\n");


            
            #line 43 "..\..\Dashboard\Pages\HomePage.cshtml"

                var exception = trace.GetException();
                if (exception != null)
                {
                    var detailStyle = first ? "" : "display: none;";

            
            #line default
            #line hidden
WriteLiteral("                    <tr class=\"detail\" style=\"");


            
            #line 48 "..\..\Dashboard\Pages\HomePage.cshtml"
                                         Write(detailStyle);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <td colspan=\"8\" style=\"padding-left: 20px; background" +
"-color: #f5f5f5;\">\r\n                            <h3>");


            
            #line 50 "..\..\Dashboard\Pages\HomePage.cshtml"
                           Write(exception.TypeName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                            <h4>");


            
            #line 51 "..\..\Dashboard\Pages\HomePage.cshtml"
                           Write(exception.Message);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                            ");


            
            #line 52 "..\..\Dashboard\Pages\HomePage.cshtml"
                       Write(Html.RenderExceptionStackTrace(exception.Detail));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");


            
            #line 55 "..\..\Dashboard\Pages\HomePage.cshtml"
                    first = false;
                }
            }

            
            #line default
            #line hidden

            
            #line 58 "..\..\Dashboard\Pages\HomePage.cshtml"
             if (this.Count == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td colspan=\"8\">No traces.</td>\r\n      " +
"          </tr>\r\n");


            
            #line 63 "..\..\Dashboard\Pages\HomePage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n");


            
            #line 67 "..\..\Dashboard\Pages\HomePage.cshtml"
Write(Html.Paginator(this.Pager));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
