#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\HomePage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\HomePage.cshtml"
    using PugTrace.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\HomePage.cshtml"
    using PugTrace.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class HomePage : TracesPage
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Dashboard\Pages\HomePage.cshtml"
  
    Layout = new LayoutPage();
    bool first = true;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"btn-toolbar btn-toolbar-top\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Dashboard\Pages\HomePage.cshtml"
Write(Html.Filter(this.Pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Dashboard\Pages\HomePage.cshtml"
Write(Html.PerPageSelector(this.Pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"search-bar\"");

WriteLiteral(" class=\"row hide\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Dashboard\Pages\HomePage.cshtml"
   Write(Html.Search(this.Pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>Application</th>
                <th>Source</th>
                <th>Id</th>
                <th>Event Type</th>
                <th>Timestamp</th>
                <th>Machine</th>
                <th>Message</th>
                <th");

WriteLiteral(" style=\"width: 70px;\"");

WriteLiteral("></th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n");

            
            #line 36 "..\..\Dashboard\Pages\HomePage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Dashboard\Pages\HomePage.cshtml"
             foreach (var trace in this.Model)
            {
                var rowClass = "trace " + trace.EventType.ToLower();


            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteAttribute("class", Tuple.Create(" class=\"", 1087), Tuple.Create("\"", 1104)
            
            #line 40 "..\..\Dashboard\Pages\HomePage.cshtml"
, Tuple.Create(Tuple.Create("", 1095), Tuple.Create<System.Object, System.Int32>(rowClass
            
            #line default
            #line hidden
, 1095), false)
);

WriteLiteral(">\r\n                    <td>");

            
            #line 41 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 42 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.Source);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 43 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 44 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.EventType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 45 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(Html.RenderDateTime(trace.UtcDateTime.ToLocalTime()));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 46 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(trace.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 47 "..\..\Dashboard\Pages\HomePage.cshtml"
                   Write(Html.Truncate(trace.Message));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1511), Tuple.Create("\"", 1561)
            
            #line 48 "..\..\Dashboard\Pages\HomePage.cshtml"
, Tuple.Create(Tuple.Create("", 1518), Tuple.Create<System.Object, System.Int32>(Url.TraceDetails(trace.TraceId.ToString())
            
            #line default
            #line hidden
, 1518), false)
);

WriteLiteral(" class=\"btn btn-xs btn-default pull-right\"");

WriteLiteral(">Details</a></td>\r\n                </tr>\r\n");

            
            #line 50 "..\..\Dashboard\Pages\HomePage.cshtml"

                var exception = trace.GetException();
                if (exception != null)
                {
                    var detailStyle = first ? "" : "display: none;";

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteLiteral(" class=\"detail\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1870), Tuple.Create("\"", 1890)
            
            #line 55 "..\..\Dashboard\Pages\HomePage.cshtml"
, Tuple.Create(Tuple.Create("", 1878), Tuple.Create<System.Object, System.Int32>(detailStyle
            
            #line default
            #line hidden
, 1878), false)
);

WriteLiteral(">\r\n                        <td");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(" style=\"padding-left: 20px; background-color: #f5f5f5;\"");

WriteLiteral(">\r\n                            <h3>");

            
            #line 57 "..\..\Dashboard\Pages\HomePage.cshtml"
                           Write(exception.TypeName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                            <h4>");

            
            #line 58 "..\..\Dashboard\Pages\HomePage.cshtml"
                           Write(exception.Message);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

WriteLiteral("                            ");

            
            #line 59 "..\..\Dashboard\Pages\HomePage.cshtml"
                       Write(Html.RenderExceptionStackTrace(exception.Detail));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 62 "..\..\Dashboard\Pages\HomePage.cshtml"
                    first = false;
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 65 "..\..\Dashboard\Pages\HomePage.cshtml"
             if (this.Count == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">No traces.</td>\r\n                </tr>\r\n");

            
            #line 70 "..\..\Dashboard\Pages\HomePage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n");

            
            #line 74 "..\..\Dashboard\Pages\HomePage.cshtml"
Write(Html.Paginator(this.Pager));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
