#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using PugTrace.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\LayoutPage.cshtml"
   
    var version = GetType().Assembly.GetName().Version;


            
            #line default
            #line hidden
WriteLiteral(@"<!DOCTYPE html>
<html lang=""en"">
<head>
    <title>PugTrace</title>
    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"">
    <meta charset=""utf-8"" />
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <link rel=""stylesheet"" href=""");


            
            #line 16 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                            Write(Url.To("/css"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
</head>
<body>
    <div class=""navbar navbar-default navbar-static-top"">
        <div class=""container-fluid"">
            <div class=""navbar-header"">
                <button type=""button"" class=""navbar-toggle"" data-toggle=""collapse"" data-target="".navbar-collapse"">
                    <span class=""icon-bar""></span>
                    <span class=""icon-bar""></span>
                    <span class=""icon-bar""></span>
                </button>
                <a class=""navbar-brand"" href=""");


            
            #line 27 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                         Write(Url.Home());

            
            #line default
            #line hidden
WriteLiteral(@""">
                    <span class=""logo""></span>
                    <span class=""title"">PugTrace</span>
                </a>
            </div>
            <div class=""collapse navbar-collapse"">
                <ul class=""nav navbar-nav navbar-right"">
                    <li>
                        <a href=""");


            
            #line 35 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                            Write(AppPath);

            
            #line default
            #line hidden
WriteLiteral(@""">
                            <span class=""glyphicon glyphicon-log-out""></span>
                            Back to site
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class=""container-fluid"" style=""margin-bottom: 20px;"">
        <div class=""white-card"" style=""margin-right: 0;"">
            ");


            
            #line 47 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
    </div>

    <div id=""footer"">
        <div class=""container-fluid"">
            <div class=""row"">
                <p class=""text-center"">
                    Powered by <a href=""https://github.com/Myslik/PugTrace"" target=""_blank"">PugTrace</a>,
                    version ");


            
            #line 56 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                       Write(String.Format("{0}.{1}.{2}", version.Major, version.Minor, version.Build));

            
            #line default
            #line hidden
WriteLiteral(". &copy; ");


            
            #line 56 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                                                                                          Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" PugTrace.\r\n                    Licensed under <a href=\"https://opensource.org/li" +
"censes/MIT\" target=\"_blank\">MIT</a>.\r\n                    Server date and time i" +
"s ");


            
            #line 58 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                       Write(DateTime.Now.ToString("f"));

            
            #line default
            #line hidden
WriteLiteral(".\r\n                    This log is provided by the ");


            
            #line 59 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                                           Write(Storage.ToString());

            
            #line default
            #line hidden
WriteLiteral(".\r\n                </p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <s" +
"cript src=\"");


            
            #line 65 "..\..\Dashboard\Pages\LayoutPage.cshtml"
            Write(Url.To("/js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script>\r\n        $(function () {\r\n            $(\".expander\").on" +
"(\"click\", function () {\r\n                $(this).closest(\".trace\").next(\".detail" +
"\").toggleClass(\"hide\");\r\n            });\r\n        });\r\n    </script>\r\n</body>\r\n<" +
"/html>");


        }
    }
}
#pragma warning restore 1591
