#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\LayoutPage.cshtml"
    using PugTrace.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class LayoutPage : RazorPage
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <title>PugTrace</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 435), Tuple.Create("\"", 457)
            
            #line 13 "..\..\Dashboard\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 442), Tuple.Create<System.Object, System.Int32>(Url.To("/css")
            
            #line default
            #line hidden
, 442), false)
);

WriteLiteral(" />\r\n</head>\r\n<body>\r\n    <!-- Wrap all page content here -->\r\n    <div");

WriteLiteral(" id=\"wrap\"");

WriteLiteral(">\r\n\r\n        <!-- Fixed navbar -->\r\n        <div");

WriteLiteral(" class=\"navbar navbar-default navbar-static-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1082), Tuple.Create("\"", 1100)
            
            #line 28 "..\..\Dashboard\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 1089), Tuple.Create<System.Object, System.Int32>(Url.Home()
            
            #line default
            #line hidden
, 1089), false)
);

WriteLiteral(">\r\n                        <img");

WriteLiteral(" class=\"logo\"");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1152), Tuple.Create("\"", 1178)
            
            #line 29 "..\..\Dashboard\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create<System.Object, System.Int32>(Url.To("/img/logo")
            
            #line default
            #line hidden
, 1158), false)
);

WriteLiteral(" />\r\n                        <span>PugTrace</span>\r\n                    </a>\r\n   " +
"             </div>\r\n                <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1459), Tuple.Create("\"", 1474)
            
            #line 36 "..\..\Dashboard\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 1466), Tuple.Create<System.Object, System.Int32>(AppPath
            
            #line default
            #line hidden
, 1466), false)
);

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"glyphicon glyphicon-log-out\"");

WriteLiteral(@"></span>
                                Back to site
                            </a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>

        <!-- Begin page content -->
        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"margin-bottom: 20px;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 49 "..\..\Dashboard\Pages\LayoutPage.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"list-inline credit\"");

WriteLiteral(">\r\n                <li>\r\n                    <span>\r\n                        PugT" +
"race\r\n");

            
            #line 59 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 59 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                          
                            var version = GetType().Assembly.GetName().Version;
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 62 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                   Write(String.Format("{0}.{1}.{2}", version.Major, version.Minor, version.Build));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n                </li>\r\n                <li>");

            
            #line 65 "..\..\Dashboard\Pages\LayoutPage.cshtml"
               Write(Storage);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                <li>Time: ");

            
            #line 66 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                     Write(DateTime.UtcNow);

            
            #line default
            #line hidden
WriteLiteral(" GMT</li>\r\n                <li>Generated: ");

            
            #line 67 "..\..\Dashboard\Pages\LayoutPage.cshtml"
                           Write(GenerationTime.Elapsed.TotalMilliseconds.ToString("N"));

            
            #line default
            #line hidden
WriteLiteral("ms</li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2675), Tuple.Create("\"", 2695)
            
            #line 72 "..\..\Dashboard\Pages\LayoutPage.cshtml"
, Tuple.Create(Tuple.Create("", 2681), Tuple.Create<System.Object, System.Int32>(Url.To("/js")
            
            #line default
            #line hidden
, 2681), false)
);

WriteLiteral(@"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>
        $(function () {
            $("".trace.error"").on(""click"", function () {
                var current = $(this).next();
                $("".detail"").not(current).hide();
                current.show();
            });
        });
    </script>
</body>
</html>");

        }
    }
}
#pragma warning restore 1591
