#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
    using PugTrace.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
    using PugTrace.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class TraceRowPage : RazorPage<Trace>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
  
    Layout = null;
    var rowClass = "trace " + Model.EventType.ToLower();
    var data = Model.GetData();


            
            #line default
            #line hidden
WriteLiteral("\r\n<tr class=\"");


            
            #line 12 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
      Write(rowClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <td style=\"width: 110px;\">\r\n        <span class=\"label label-default\">");


            
            #line 14 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
                                     Write(Html.RenderDateTime(Model.UtcDateTime.ToLocalTime()));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </td>\r\n    <td style=\"width: 140px;\">\r\n        ");


            
            #line 17 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
   Write(Model.PrincipalIdentityName);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n    <td>\r\n");


            
            #line 20 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
         if (data != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <a href=\"#\" class=\"btn btn-xs btn-default pull-right expander\">Expand" +
"</a>\r\n");


            
            #line 23 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");


            
            #line 24 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
   Write(Html.Raw(Model.GetMessage()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n</tr>\r\n\r\n");


            
            #line 28 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
 if (data != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <tr class=\"detail hide\">\r\n        <td colspan=\"3\">\r\n            ");


            
            #line 32 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
       Write(Html.RenderExceptionStackTrace(data.StackTrace));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 34 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
             if (data.Parameters.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <dl class=\"dl-horizontal\">\r\n");


            
            #line 37 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
                     foreach (var parameter in data.Parameters)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <dt>");


            
            #line 39 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
                       Write(parameter.Key);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n");



WriteLiteral("                        <dd>");


            
            #line 40 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
                       Write(parameter.Value);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n");


            
            #line 41 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </dl>\r\n");


            
            #line 43 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n    </tr>\r\n");


            
            #line 46 "..\..\Dashboard\Pages\TraceRowPage.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
