#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PugTrace.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
    using PugTrace.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
    using PugTrace.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
    using PugTrace.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class TraceDetailsPage : RazorPage<TraceData>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
  
    Layout = new LayoutPage();


            
            #line default
            #line hidden
WriteLiteral("<dl class=\"dl-horizontal\">\r\n    <dt>Application</dt>\r\n    <dd>");


            
            #line 11 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
   Write(Model.ApplicationName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Source</dt>\r\n    <dd>");


            
            #line 13 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
   Write(Model.Source);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Id</dt>\r\n    <dd>");


            
            #line 15 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
   Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Event Type</dt>\r\n    <dd>");


            
            #line 17 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
   Write(Model.EventType);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Timestamp</dt>\r\n    <dd>");


            
            #line 19 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
   Write(Model.UtcDateTime.ToString("f"));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Machine</dt>\r\n    <dd>");


            
            #line 21 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
   Write(Model.MachineName);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n");


            
            #line 22 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
     if (!string.IsNullOrEmpty(Model.Message))
    {

            
            #line default
            #line hidden
WriteLiteral("        <dt>Message</dt>\r\n");



WriteLiteral("        <dd>");


            
            #line 25 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
       Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n");


            
            #line 26 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</dl>\r\n\r\n");


            
            #line 29 "..\..\Dashboard\Pages\TraceDetailsPage.cshtml"
Write(Html.RenderData(Model.Data));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
